name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails_version: ['main']
        ruby_version: ['truffleruby-head', '3.1']
        exclude:
          - rails_version: '5.2.6'
            ruby_version: '3.0'
          - rails_version: '5.2.6'
            ruby_version: '3.1'
          - rails_version: '6.0.4.4'
            ruby_version: '3.0'
          - rails_version: '6.0.4.4'
            ruby_version: '3.1'
          - rails_version: '7.0.2.3'
            ruby_version: '2.5'
          - rails_version: '7.0.2.3'
            ruby_version: '2.6'
          - rails_version: 'main'
            ruby_version: '2.5'
          - rails_version: 'main'
            ruby_version: '2.6'
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-${{ matrix.rails_version }}-ruby-${{ matrix.ruby_version }}-${{ hashFiles('**/Gemfile.lock') }}
    - name: Build and test with Rake
      run: |
        bundle config path vendor/bundle
        bundle update
        bundle exec rake test spec
      env:
        RAISE_ON_WARNING: 1
        MEASURE_COVERAGE: true
        RAILS_VERSION: ${{ matrix.rails_version }}
